# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: ODhmMGJiY2ZhZjdlNGIzYmI3NWI4MzhjZWU4OTEzMmVkNTIwZTM2NjI5MWNhYjI3YjdjZjk0ZWViMDAwOWZjNzUyYzE5ODZkN2M3NTYwNTRmZDhlM2Q4MTE2OWFkNGFmZjhiODE1NGZmOTJkZDM3ZTRiZjVkY2M1ZDM2YjUyYzA=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
